


#
#	DEFAULT OS IS WINDOWS 
#
D_OF = -DWindows
SPARSELIB_DIR			= c:/users/eero/programming/SparseLib++/1.7
SPARSELIB_INCLUDE_DIR		= $(SPARSELIB_DIR)/include
SPARSELIB_MV_INCLUDE_DIR	= $(SPARSELIB_DIR)/mv/include
SPARSELIBINCS = -I$(SPARSELIB_INCLUDE_DIR) -I$(SPARSELIB_MV_INCLUDE_DIR)

# not needed anymore. inlcudes are defined in ./src/makefile
#QLC3D_PATH      = c:/users/eero/programming/qlc3d_git/qlc3d



#
#
#	DETECT IF LINUX
#
#
UNAME = $(shell uname)
ifeq ($(UNAME), Linux)
	QLC3D_PATH  = $(CURDIR)/..
	SPARSELIB_DIR			= /home/eero/programming/libs/SparseLib++/1.7
	SPARSELIB_INCLUDE_DIR		= $(SPARSELIB_DIR)/include/
	SPARSELIB_MV_INCLUDE_DIR	= $(SPARSELIB_DIR)/mv/include/
	D_OF = -DLinux
		
endif

QLC3D_INCS		= -I$(QLC3D_PATH)/includes


INCLUDES 		= $(SPARSELIBINCS) $(QLC3D_INCS)

CCCFLAGS =    '-DCOMPLEX=std::complex<double>'

# THIS SET OF FLAGS (WITH -O3) RESULTS IN UNEXPLAINED RUNTIME CRASH. 
#CFLAGS =  -march=native -mtune=native -O3 -ffast-math -Wall -fopenmp -funroll-loops

# BELOW FLAGS IS EQUIVALENT TO -O3, BUT TREE VECTORIZE IS DISABLED
CFLAGS+= -Wall -Wextra -fopenmp -march=native -mtune=native -O3 -fno-tree-vectorize \
		


LDFLAGS	 = $(SPARSELIB_DIR)/lib/libsparse.a \
           $(SPARSELIB_DIR)/lib/libspblas.a \
           $(SPARSELIB_DIR)/lib/libmv.a -lm
